# Generated by Django 6.0.4 on 2026-05-12 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sales', to='api.appointment'),
        ),
    ]
