# Generated by Django 5.2.14 on 2026-06-16 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_payment_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField()),
                ('preferred_period', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('any', 'Qualquer horário')], default='any', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Aguardando'), ('contacted', 'Contactado'), ('scheduled', 'Agendado'), ('cancelled', 'Cancelado')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_as_barber', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_as_client', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
