# Generated by Django 6.0.4 on 2026-07-02 00:19

from django.db import migrations, models

def copy_services(apps, schema_editor):
    Appointment = apps.get_model('api', 'Appointment')
    WaitlistEntry = apps.get_model('api', 'WaitlistEntry')
    
    for app in Appointment.objects.all():
        if hasattr(app, 'service_id') and app.service_id:
            app.services.add(app.service_id)
            
    for entry in WaitlistEntry.objects.all():
        if hasattr(entry, 'service_id') and entry.service_id:
            entry.services.add(entry.service_id)

def reverse_copy_services(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(blank=True, to='api.service'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='services',
            field=models.ManyToManyField(blank=True, to='api.service'),
        ),
        migrations.RunPython(copy_services, reverse_copy_services),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='historicalappointment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='service',
        ),
    ]
