# Generated by Django 5.2.14 on 2026-08-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_appointment_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
