# Generated by Django 5.2.14 on 2026-08-31 15:03

from django.db import migrations, models


def backfill_bookable(apps, schema_editor):
    User = apps.get_model('api', 'User')
    User.objects.filter(role='barber').update(is_bookable=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_historicaluser_must_change_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_bookable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_bookable',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_bookable, noop),
    ]
