# Generated by Django 5.2.14 on 2026-08-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_historicaluser_is_bookable_user_is_bookable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_payment', models.BooleanField(default=False)),
                ('infinitepay_handle', models.CharField(blank=True, default='', max_length=100)),
                ('hold_minutes', models.PositiveIntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de pagamento do agendamento',
                'verbose_name_plural': 'Configuração de pagamento do agendamento',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_amount_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_checkout_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_order_nsu',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_slug',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Não exigido'), ('pending', 'Aguardando pagamento'), ('paid', 'Pago')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_transaction_nsu',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='payment_amount_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='payment_checkout_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='payment_order_nsu',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='payment_slug',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Não exigido'), ('pending', 'Aguardando pagamento'), ('paid', 'Pago')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='payment_transaction_nsu',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
