# Generated by Django 5.2.14 on 2026-08-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_bookingpaymentconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_capture_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='payment_capture_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
