# Generated by Django 5.2.14 on 2026-09-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_appointment_payment_capture_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpaymentconfig',
            name='require_payment',
        ),
        migrations.AddField(
            model_name='bookingpaymentconfig',
            name='payment_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
