# Generated by Django 5.2.14 on 2026-09-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_bookingpaymentconfig_require_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPriceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_price_days', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de valores especiais',
                'verbose_name_plural': 'Configuração de valores especiais',
            },
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
