# Generated by Django 5.2.16 on 2026-10-08 23:36

import django.utils.timezone
from django.db import migrations, models


def backfill_completed_at(apps, schema_editor):
    Appointment = apps.get_model('api', 'Appointment')
    for appointment in Appointment.objects.filter(status='completed', completed_at__isnull=True).iterator():
        appointment.completed_at = appointment.updated_at
        appointment.save(update_fields=['completed_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_bookingpaymentconfig_deposit_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAutomationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_enabled', models.BooleanField(default=True)),
                ('follow_up_template', models.TextField(default='Olá {nome}! 💛\n\nPassando para saber como você está se sentindo após o procedimento de {servico}. Está tudo bem? Se precisar de alguma orientação, estou por aqui.')),
                ('follow_up_enabled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_enabled', models.BooleanField(default=True)),
                ('review_template', models.TextField(default='Olá {nome}! ✨\n\nFoi um prazer cuidar de você no seu primeiro procedimento na Milly Rodrigues. Sua opinião é muito importante para nós. Você pode deixar sua avaliação aqui?\n\n⭐ {link_avaliacao}')),
                ('review_enabled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('google_review_url', models.URLField(blank=True, default='', max_length=1000)),
                ('return_enabled', models.BooleanField(default=True)),
                ('return_template', models.TextField(default='Olá {nome}! 🌷\n\nJá se passaram 30 dias desde o seu procedimento de {servico}. Está na hora de renovar esse cuidado. Agende seu próximo horário:\n\n📅 {link_agendamento}')),
                ('return_enabled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de mensagens automáticas',
                'verbose_name_plural': 'Configuração de mensagens automáticas',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_completed_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('barber', 'Profissional'), ('receptionist', 'Receptionist'), ('client', 'Client')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('confirmation', 'Confirmação'), ('reminder', 'Lembrete'), ('cancellation', 'Cancelamento'), ('follow_up', 'Acompanhamento pós-procedimento'), ('review_request', 'Pedido de avaliação'), ('return_reminder', 'Lembrete de retorno')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('barber', 'Profissional'), ('receptionist', 'Receptionist'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
