# Generated by Django 5.2.16 on 2026-10-08 23:45

from django.db import migrations, models


def create_default_automation_config(apps, schema_editor):
    """Fixa o início da automação no deploy, antes da primeira execução do cron."""
    MessageAutomationConfig = apps.get_model('api', 'MessageAutomationConfig')
    MessageAutomationConfig.objects.get_or_create(pk=1)


def reclassify_thank_you_notifications(apps, schema_editor):
    """Agradecimentos antigos eram gravados como 'confirmation'."""
    Notification = apps.get_model('api', 'Notification')
    Notification.objects.filter(
        type='confirmation', message__icontains='Obrigado pela visita',
    ).update(type='thank_you')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_messageautomationconfig_appointment_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageautomationconfig',
            name='appointment_reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messageautomationconfig',
            name='appointment_reminder_template',
            field=models.TextField(default='⏰ *Lembrete de Agendamento*\n\nOlá {nome}! Passando para lembrar do seu horário hoje:\n\n✨ *{servico}*\n🕒 às *{hora}*\ncom *{profissional}*\n\n📍 *Lembrete:* Chegue com 10 minutos de antecedência.\n\n🔗 *Gerenciar agendamento:* {link_gerenciamento}\n\nAté logo! ✨'),
        ),
        migrations.AddField(
            model_name='messageautomationconfig',
            name='cancellation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messageautomationconfig',
            name='cancellation_template',
            field=models.TextField(default='❌ *Agendamento Cancelado*\n\nOlá {nome}, o seu agendamento para *{servico}* no dia {data} às {hora} foi cancelado.\n\nCaso queira agendar um novo horário, acesse: {link_agendamento}'),
        ),
        migrations.AddField(
            model_name='messageautomationconfig',
            name='confirmation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messageautomationconfig',
            name='confirmation_template',
            field=models.TextField(default='✅ *Agendamento Confirmado*\n\nOlá {nome},\nSeu agendamento para *{servico}* foi confirmado!\n\n📅 *Data:* {data}\n⏰ *Hora:* {hora}\n✨ *Profissional:* {profissional}\n\n📍 *Local:* Milly Rodrigues — Depilação & Estética\n⚠️ *Importante:* Pedimos a gentileza de chegar com *10 minutos de antecedência*.\n\n🔗 *Veja ou cancele em:* {link_gerenciamento}\n\nEsperamos por você! ✨'),
        ),
        migrations.AddField(
            model_name='messageautomationconfig',
            name='thank_you_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messageautomationconfig',
            name='thank_you_template',
            field=models.TextField(default='⭐ *Obrigado pela visita!*\n\nOlá {nome},\nObrigado por escolher a Milly Rodrigues! Esperamos que tenha gostado do serviço *{servico}*.\n\n🔗 *Acompanhe seu histórico:* {link_gerenciamento}\n\nAté a próxima! ✨'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('confirmation', 'Confirmação'), ('reminder', 'Lembrete'), ('cancellation', 'Cancelamento'), ('follow_up', 'Acompanhamento pós-procedimento'), ('review_request', 'Pedido de avaliação'), ('return_reminder', 'Lembrete de retorno'), ('thank_you', 'Agradecimento')], max_length=20),
        ),
        migrations.RunPython(create_default_automation_config, migrations.RunPython.noop),
        migrations.RunPython(reclassify_thank_you_notifications, migrations.RunPython.noop),
    ]
